### ISSUE TITLE
Valeur nutritionnelle des aliments ne sont pas affichées

### ISSUE THREAD

**Issue by Tri125** [Nutritia/nutritia#145]
@Nutritia/developers 

Sa viend du commit ddaf5836004aea878f5dc99b8655bcdfc8561bfa de Corantin.
Je n'ai pas travaillé sur le côté nutritionnelle avant, donc j'ai un peu de la difficulté à comprendre ce qui a été modifié qui pourrait causer le problème.

Méthode de reproduction:
1.  Aller dans le menu calculatrice nutritionnelle
2.  Chercher pour un aliment (Ail, Pomme, etc.)
3. Hover sur l'aliment(s), le tooltip affiche toutes les valeurs à 0.

**Comment by Tri125** [comment]
Je pense l'avoir arrangé dans 9b03066df1628cbb44fde229785ab5d8154b8b0e (en attente de merge). Faudrait juste me confirmer que les valeurs font du sens.

**Comment by Corantin** [comment]
Jarrive aujourd'hui
