### ISSUE TITLE
Exception lorsqu'on log avec un compte avec date anniversaire vide

### ISSUE THREAD

**Issue by Tri125** [Nutritia/nutritia#35]
MySqlConnexion.cs et FenetreConnexion.xaml.cs

Plante à la méthode Query à la ligne 138.

J'imagine que c'est juste en général. Je sais qu'il plante lorsque le membre dans la BD à une date de naissance à 0000-00-00:

Unable to convert MySQL date/time value to System.DateTime

**Comment by Tri125** [comment]
J'ai testé avec un mot de passe vide et sa marche (autre que la fenêtre Connexion qui te bloque même si le compte n'a pas de mot de passe...).

Alors, sa pointe vers la direction que c'est seulement pour la date.

**Comment by Tri125** [comment]
@Corantin 

J'ai remarqué que la méthode Update de MySqlMembreService.cs rajouté dans le commit 40cf9c24 écrase dateNaissance à '0000-00-00' du membre qui est updaté. Sa fais rencontrer la même exception tel que décris en haut (vas sur le site web corantin pour tout lire :p ).

**Comment by Tri125** [comment]
J'ai vérifié la date du membre passé en paramètre à Update et c'est beau de ce côté là.

**Comment by Tri125** [comment]
Okay, la requête est mal formé je pense.
Le string de DateTime en C# donne '2/12/2015 12:00:00 AM'
Ce qui donne un warning sur MySql: Data truncated et sa le met à 0000-00-00.

Le string fourni devrait être '2015-12-2' on peut fournir l'heure, mais sa va être truncate vu que c'est un type Date en BD.

Sa explique pourquoi la donné est changé incorrectement dans la BD, mais pas l'exception dans C#.

J'imagine que c'est juste une valeur invalide dans C#.

**Comment by Tri125** [comment]
Je pense que le bug est aussi dans la méthode Insert, le format de la date n'est pas ajusté pour MySql avant de former la requête.

**Comment by Tri125** [comment]
@glesaux je te mentionne pour te mettre au courant parce que je crois que c'est toi qui a fait l'Insert.

**Comment by Tri125** [comment]
Format réglé dans le commit 65625f921b822a594e9ea9213b5e7694950eedfe

**Comment by glesaux** [comment]
Ah okok dsl j'avais pas catché que c'était linsert

**Comment by Corantin** [comment]
C tu réglé la ? Pi la conmnexion à la BD ne fonctionne pas

2015-10-25 9:56 GMT-04:00 glesaux notifications@github.com:

> Ah okok dsl j'avais pas catché que c'était linsert
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Nutritia/nutritia/issues/35#issuecomment-150925926.

## 

Corantin Noll

**Comment by Tri125** [comment]
Ce n'est pas lié Corantin. Sa c'est que depuis le pull #40 la config de BD est rendu local.
Donc, soit tu l'installe localement et tu fais en sorte d'avoir le nom du schema, l'usager root et sans password, soit tu modifies le fichier, mais que tu ne commit pas dessus.

**Comment by Tri125** [comment]
Well, sa plante sans doute parce que
'0000-00-00' est plus petit que DateTime.MinValue qui est la valeur la plus petite de DateTime en C# (évalué à 00:00:00.0000000 UTC, Janvier 1, 0001)

**Comment by Tri125** [comment]
L'utilisation normal de l'application ne permet pas d'insérer une donnée date invalid.
WontFix.
