### ISSUE TITLE
RessourceDictionary à chaque fenêtre, utile?

### ISSUE THREAD

**Issue by Tri125** [Nutritia/nutritia#36]
Je l'ai enlevé d'une fenêtre pour essayer et le style sur les boutons étaient toujours là quand même.
Aucune erreur.

@Corantin peut-être que tu peux répondre à la question.

**Comment by Corantin** [comment]
Une fenetre avec des boutons ?

**Comment by Tri125** [comment]
Tu avais rajouté

```
    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="../Ressources/Ressource.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>
```

À plus ou moins chaque fenêtres.

Ressource.xaml rajoute ce style aux boutons:

```
    <Style TargetType="Button">
        <Setter Property="Button.Background" Value="Transparent" />
        <Setter Property="Button.BorderBrush" Value="Transparent" />
    </Style>
```

Le style s'applique même si tu enlève la balise UserControl.Resources aux UserControls, sauf si je me trompe. Dans le teste que j'ai fais le style s'appliquait quand même.

**Comment by Tri125** [comment]
C'est juste quand tu tu réfère à un x:key à partir du ResourceDictionary qu'il va chialer (Tout les style sauf les boutons en gros).

Sauf que tu te sauve 7 lignes redundante sur tout les fichiers si tu enlève

```
    <UserControl.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="../Ressources/Ressource.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </UserControl.Resources>
```

de chaque fenêtre pour juste mettre ces lignes une fois dans l'application sous App.xml:

```
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="UI/Ressources/Ressource.xaml"/>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
```

Sa sauve de la redondance en maudit.

**Comment by Corantin** [comment]
Je sais mais justement jai des x:key

**Comment by Tri125** [comment]
Regarde mon pull request #38, je sauve 113 lignes inutiles.

**Comment by Tri125** [comment]
Changement intégré.
