### ISSUE TITLE
Écrire un README pour la connexion bd

### ISSUE THREAD

**Issue by Tri125** [Nutritia/nutritia#58]

**Comment by glesaux** [comment]
Je suis en train d'en écrire un.

**Comment by Tri125** [comment]
Si tu le nomme README.md le contenu sera affiché automatiquement sur la page du projet sur gitHub et tu pourrais l'écrire en [markdown](https://guides.github.com/features/mastering-markdown/).

**Comment by Tri125** [comment]
Rajouté dans a377e3a4e20efd47174274f5f2423af697896d29
